targets:
  $default:
    builders:
      slang_build_runner:
        options:
          base_locale: en
          input_directory: assets/i18n
          namespaces: true
          timestamp: false

global_options:
  json_serializable:
    runs_before:
      - retrofit_generator
