name: ziggle
description: ziggle
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  cached_network_image: ^3.2.3
  dio: ^5.2.1+1
  flutter:
    sdk: flutter
  flutter_html: ^3.0.0-beta.2
  flutter_native_splash: ^2.3.1
  flutter_web_auth_2: ^2.1.5
  freezed_annotation: ^2.2.0
  get: ^4.6.5
  intl: ^0.18.1
  json_annotation: ^4.8.1
  retrofit: ^4.0.1
  url_launcher: ^6.1.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.0
  retrofit_generator: ^7.0.7
  flutter_launcher_icons: ^0.13.1
  flutter_gen_runner: ^5.3.1

flutter:
  uses-material-design: true
  assets:
    - assets/logo/icon.png
    - assets/icons/
  fonts:
    - family: NotoSansKR
      fonts:
        - asset: assets/fonts/NotoSansKR-Regular.otf
          weight: 400
        - asset: assets/fonts/NotoSansKR-Medium.otf
          weight: 500
        - asset: assets/fonts/NotoSansKR-Bold.otf
          weight: 700
