name: build test ios

on:
  pull_request:
    branches:
      - main
      - development
    paths-ignore:
      - 'android/**'
      - 'lib/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'

jobs:
  build-and-test:
    name: Build Android App and Test
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No build required"'
