name: build and publish to Play Store

on:
  push:
    branches:
      - development

jobs:
  build-and-upload:
    name: Build Android App and Upload
    runs-on: ubuntu-latest
    concurrency:
      group: android-staging
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3

      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.0-0.2.pre'
          channel: 'beta'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'

      - name: Write Keystore
        run: |
          echo ${{ secrets.KEYSTORE }} | base64 --decode > ./android/app/upload-keystore.jks
          echo "${{ secrets.KEYSTORE_PROPERTIES }}" > ./android/key.properties
        env:
          KEYSTORE: ${{ secrets.KEYSTORE }}
          KEYSTORE_PROPERTIES: ${{ secrets.KEYSTORE_PROPERTIES }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2.0'

      - name: Run fastlane
        run: |
          bundle install
          bundle exec fastlane internal
        env:
          SUPPLY_JSON_KEY_DATA: ${{ secrets.SUPPLY_JSON_KEY_DATA }}
          SLACK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
          SLACK_CHANNEL: ${{ secrets.SLACK_CHANNEL }}
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
        working-directory: ./android

      - name: action-slack
        uses: 8398a7/action-slack@v3
        if: ${{ failure() || cancelled() }}
        with:
          status: ${{ job.status }}
          author_name: Github Action Build
          mention: ${{ secrets.SLACK_MENTION }}
          if_mention: 'failure,cancelled'
          fields: repo,message,commit,author,action,eventName,ref,workflow,job,took
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
