name: build test ios

on:
  pull_request:
    branches:
      - main
      - development

jobs:
  build-and-test:
    name: Build iOS App and Test
    runs-on: macos-latest
    concurrency:
      group: ios-test-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Changed Files
        uses: tj-actions/changed-files@v37.5.0
        id: changed-files
        with:
          files: |
            pubspec.yaml
            pubspec.lock
            ios/**
            lib/**

      - uses: subosito/flutter-action@v2
        if: steps.changed-files.outputs.any_changed == 'true'
        with:
          flutter-version: '3.13.0-0.2.pre'
          channel: 'beta'
          cache: true
          cache-key: 'flutter-:os:-:channel:-:version:-:arch:-:hash:'
          cache-path: '${{ runner.tool_cache }}/flutter/:channel:-:version:-:arch:'

      - name: Run fastlane
        if: steps.changed-files.outputs.any_changed == 'true'
        run: |
          bundle install
          bundle exec fastlane test
        working-directory: ./ios
