name: build test

on:
  pull_request:
    branches:
      - main
      - development
    paths-ignore:
      - 'ios/**'
      - 'lib/**'
      - 'pubspec.yaml'
      - 'pubspec.lock'

jobs:
  build-and-test:
    name: Build iOS App and Test
    runs-on: ubuntu-latest
    concurrency:
      group: ios-test-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    steps:
      - run: 'echo "No build required"'
